{% set name = "SRHpylibs" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/srhartono/{{ name[0] }}/{{ name[0] }}-{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - SRHpylibs

about:
  home: https://github.com/srhartono/
  license: BSD
  license_family: BSD
  summary: SRHpylibs
